<?php

namespace GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Demande_FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Demande_FormationRepository extends EntityRepository
{

    function demandeFormationCount($month){
        $qb = $this->createQueryBuilder('df');

        $qb->select('count(df)');

        $year = date("Y");

        $qb->where("df.dateSouhaite >= '$year-$month-01'");

        $qb->andWhere("df.dateSouhaite <= '$year-$month-31'");


        return $qb->getQuery()->getSingleScalarResult();
    }
}
