<?php

namespace GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DemandeCongeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeCongeRepository extends EntityRepository
{


    function demandeCongeCount($month){
        $qb = $this->createQueryBuilder('d');

        $qb->select('count(d)');

        $year = date("Y");



        $qb->where("d.dateDebutConge >= '$year-$month-01'");
        $qb->andWhere("d.dateFinConge <= '$year-$month-31'");

        return $qb->getQuery()->getSingleScalarResult();
    }

}
