<?php

namespace GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FichierJoinsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichierJoinsRepository extends EntityRepository
{
}
