<?php

namespace GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends EntityRepository
{

    function formationCount($month){
        $qb = $this->createQueryBuilder('f');

        $qb->select('count(f)');

        $year = date("Y");

        $qb->where("f.dateDebut >= '$year-$month-01'");

        $qb->andWhere("f.dateFin <= '$year-$month-31'");

        return $qb->getQuery()->getSingleScalarResult();
    }
}
