<?php

namespace GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FormationComplementaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationComplementaireRepository extends EntityRepository
{
}
