
gestion_poste:
    resource: "@GestionBundle/Controller/PosteController.php"
    type:     annotation

gestion_discpline:
    resource: "@GestionBundle/Controller/DiscplineController.php"
    type:     annotation

gestion_intergration:
    resource: "@GestionBundle/Controller/IntergrationController.php"
    type:     annotation

gestion_demande_conge:
    resource: "@GestionBundle/Controller/DemandeCongeController.php"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
user_active_desactive:
    path:     /{id}/active
    defaults: { _controller: GestionBundle:Employee:active }

gestion_formation_complementaire:
    resource: "@GestionBundle/Controller/FormationComplementaireController.php"
    type:     annotation


gestion_fichier:
    resource: "@GestionBundle/Controller/FichierController.php"
    type:     annotation


gestion_evaluation:
    resource: "@GestionBundle/Controller/EvaluationController.php"
    type:     annotation


gestion_nature:
    resource: "@GestionBundle/Controller/NatureController.php"
    type:     annotation

gestion_formateur:
    resource: "@GestionBundle/Controller/FormateurController.php"
    type:     annotation

gestion_produit:
    resource: "@GestionBundle/Controller/ProduitController.php"
    type:     annotation

gestion_departement:
    resource: "@GestionBundle/Controller/DepartementController.php"
    type:     annotation


gestion_type.formation:
    resource: "@GestionBundle/Controller/Type_FormationController.php"
    type:     annotation

gestion_type.contrat:
    resource: "@GestionBundle/Controller/Type_ContratController.php"
    type:     annotation

gestion_type.conge:
    resource: "@GestionBundle/Controller/Type_CongeController.php"
    type:     annotation

gestion_site:
    resource: "@GestionBundle/Controller/SiteController.php"
    type:     annotation



gestion_nature_absence:
    resource: "@GestionBundle/Controller/NatureAbsenceController.php"
    type:     annotation



gestion_formation:
    resource: "@GestionBundle/Controller/FormationController.php"
    type:     annotation

gestion_fonction:
    resource: "@GestionBundle/Controller/FonctionController.php"
    type:     annotation

gestion_demande.formation:
    resource: "@GestionBundle/Controller/Demande_FormationController.php"
    type:     annotation



gestion_carriere:
    resource: "@GestionBundle/Controller/CarriereController.php"
    type:     annotation



gestion_absence:
    resource: "@GestionBundle/Controller/AbsenceController.php"
    type:     annotation

gestion_employee:
    resource: "@GestionBundle/Controller/EmployeeController.php"
    type:     annotation

gestion_employee:
    resource: "@GestionBundle/Controller/EmployeeController.php"
    type:     annotation

gestion:
    resource: "@GestionBundle/Resources/config/routing.yml"
    prefix:   /
